api:
  - url: http://${DOMAIN}/api/plugin/volcengine-ocr
    name: volcengine-ocr
    description: æ ¹æ®ç”¨æˆ·æä¾›çš„å›¾ç‰‡ä½¿ç”¨ç«å±±å¼•æ“OCRè¯†åˆ«å†…å®¹
    parameters:
      type: object
      required:
        - image_url
      properties:
        image_url:
          description: ç”¨æˆ·æä¾›çš„å›¾ç‰‡url
          type: string
identifier: chat-plugin-volcengine-ocr
author: jqllxew
gateway: http://${DOMAIN}/api/plugin/gateway
homepage: https://github.com/jqllxew/jiujiuchat
meta:
  avatar: ğŸ“¸
  tag: test-template
  title: å›¾åƒè¯†åˆ«è¾…åŠ©
  description: å›¾åƒOCRè¯†åˆ«
version: "1"
